sudo: false
cache: bundler
language: node_js
node_js:
  - 'iojs'
  - "0.12"
  - "0.10"

script: grunt test

before_install:
  - export CHROME_BIN=chromium-browser
  - npm install -g grunt-cli bower karma
  - gem install bundler
  - bundle install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  - bower install
